### ISSUE TITLE
Error 500 Not working on Dolibarr 5.03

### ISSUE THREAD

**Issue by NoslenZuir** [TECLIB/dolibarr#4]
This module is not working on Dolibarr 5.03, I did everything and it appears but it crashes when clicking in configure "error 500". It seems to be a compatibility problem because is working on Dolibarr 5.01 but I can't use that one.

Please, I'm stucked here

**Comment by eldy** [comment]
Can you take a look into log of apache server error.log, just after the error 500 appears ?

**Comment by NoslenZuir** [comment]
It worked, permissions were the problem. But now that I'm configuring it, I have a different  problem.

There is nothing in the combo box "Products Category" and "Costumer Category". I already enabled Tags/Categories module

it should look like this: https://www.dolistore.com/2759-thickbox_default/ecommerceng-for-magento.jpg

but instead it look like this: http://imgur.com/a/qXxTi

Thank you for the answer.

**Comment by futurehousestore** [comment]
NoslenZuir you need to add New tag/category in Products/Services section and New tag/category in Third party section to see it in the drop down list in your ECommerce Sync settings.
